---
title: "Prerequisites for Intro to Frequentist and Bayesian mixed models course"
author: "Andrew Parnell"
output: html_document
---

In preparation for the course please install the following, preferably in the below suggested order. Make sure you run these before you arrive in case of poor (or crowded!) internet.

Remember you will need to bring your own personal computer for the duration of the course. 

### Step 1

Install theses packages by following the links

-	R: [www.r-project.org](http://www.r-project.org)

-	Rstudio (optional but recommended): [www.rstudio.com](https://www.rstudio.com)

-	JAGS: [sourceforge.net/projects/mcmc-jags/files/](http://sourceforge.net/projects/mcmc-jags/files/)

- If you're using Windows you also need to install the correct version of [Rtools](https://cran.r-project.org/bin/windows/Rtools/) to match your R version

If you have installed any of these previously please make sure you have the most up-to-date versions. 

### Step 2

Now install the following packages by going into Rstudio (or R) by typing:
```{r,eval=FALSE}
install.packages(c('rjags','R2jags','rmutil','boot','rstan','rstanarm','lme4'))
```

Note: this might take a while as these are pretty big and complicated packages.

Once you have installed these I would recommend checking the [rstan installation guide](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started) to check everything is working

### Troubleshooting

If you run into any problems please drop me a line at <andrew.parnell@mu.ie>.

